In [38]:
import numpy as np
import pandas as pd
from datetime import datetime

In [2]:
df_dia = pd.read_csv("Trafego_CSV/L1/01c/01.csv")

In [128]:
# '.head()' para visualizar 
# as primeiras 3 linhas de um DataFrame
print(df_dia.head(3))

  Lote   Ano  Mes  Dia  Hora  Minuto  Segundo  Local  Faixa  Entrefaixa  \
0   L1  2017   12   31    23      56       31   6601      1           0   
1   L1  2017   12   31    23      58       23   6601      1           0   
2   L1  2017   12   31    23      59       27   6601      1           0   

   Registro  Tipo de Registro    Placa  Especie  Classe  Comprimento  \
0    155620                 0                 1       0           38   
1    155621                 0  DIP9412        1       0           35   
2    155622                 0                 0       0            5   

   Velocidade  Ocupacao  Velocidade Media;  
0         108      1025                  0  
1          63      1561                  0  
2         100       776                  0  


In [46]:
# '.drop()' para deletar a coluna de placas
df_dia.drop(['Placa'], axis=1).tail(3)

Lote   Ano  Mes  Dia  Hora  Minuto  Segundo  Local  Faixa  Entrefaixa  \
3394047   L1  2018    1    1    23      59       49   7178      3           0   
3394048   L1  2018    1    1    23      59       55   7178      3           0   
3394049   L1  2018    1    1    23      59       56   7178      3           0   

         Registro  Tipo de Registro  Especie  Classe  Comprimento  Velocidade  \
3394047     29775                 0        1       0           45         178   
3394048     29776                 0        1       0           45         167   
3394049     29777                 0        1       0           46         172   

         Ocupacao  Velocidade Media;  
3394047       249                  0  
3394048       259                181  
3394049       265                181

In [30]:
# '.iloc[]' para fazer um slice do DataFrame,
# ignorando a ultima coluna
df_dia.drop(['Placa'], axis=1).iloc[:,:-1].head(3)

Lote   Ano  Mes  Dia  Hora  Minuto  Segundo  Local  Faixa  Entrefaixa  \
0   L1  2017   12   31    23      56       31   6601      1           0   
1   L1  2017   12   31    23      58       23   6601      1           0   
2   L1  2017   12   31    23      59       27   6601      1           0   

   Registro  Tipo de Registro  Especie  Classe  Comprimento  Velocidade  \
0    155620                 0        1       0           38         108   
1    155621                 0        1       0           35          63   
2    155622                 0        0       0            5         100   

   Ocupacao  
0      1025  
1      1561  
2       776

In [31]:
# Cria um segundo Dataframe, que possuira
# Uma coluna com rotulos
df_dia_atualizado = df_dia.drop(['Placa'], axis=1).iloc[:,:-1]

In [77]:
#inicio do ano
ida = datetime(2018, 1, 1, 0, 0)

def data2min (YYYY, MM, DD, hh, mm, i=ida):
    '''Recebe uma informacao de
    Data e Hora e calcula a quantidade
    de minutos necessarios para aquela
    data partindo do inicio do ano.
    (MM/DD - hh:mm) -> mmmm'''
    
    data = datetime(YYYY, MM, DD, hh, mm)
    dff = data-ida
    
    return int(dff.total_seconds()/60)

In [81]:
data2min(2018, 1, 2, 0, 0)

1440

In [110]:
for x in df_dia.loc[1:4,'Ano':'Minuto'].values :
    print(x, *x)

[2017   12   31   23   58] 2017 12 31 23 58
[2017   12   31   23   59] 2017 12 31 23 59
[2017   12   31   23   59] 2017 12 31 23 59
[2017   12   31   23   59] 2017 12 31 23 59


In [118]:
rotulos = []
for x in df_dia.loc[1:10,'Ano':'Minuto'].values :
    rotulos.append(data2min(*x))
print(rotulos)

[-2, -1, -1, -1, -1, 0, 0, 0, 2, 4]


In [124]:
def rotular_df(df):
    rotulos = []
    for x in df.loc[1:10,'Ano':'Minuto'].values :
        rotulos.append(data2min(*x))
    return rotulos

In [103]:
def f(a, b, c, d): print(a, b, c, d, sep = '&')

In [105]:
f(*np.array([1, 2, 3, 4]))

1&2&3&4


In [116]:
f(*[1, 2, 3, 4])

1&2&3&4


In [120]:
df_dia_teste = df_dia.drop(['Placa'], axis=1).iloc[1:10,:-1]
df_dia_teste

Lote   Ano  Mes  Dia  Hora  Minuto  Segundo  Local  Faixa  Entrefaixa  \
1   L1  2017   12   31    23      58       23   6601      1           0   
2   L1  2017   12   31    23      59       27   6601      1           0   
3   L1  2017   12   31    23      59       42   6601      1           0   
4   L1  2017   12   31    23      59       48   6601      1           0   
5   L1  2017   12   31    23      59       56   6601      1           0   
6   L1  2018    1    1     0       0        0   6601      1           0   
7   L1  2018    1    1     0       0       33   6601      1           0   
8   L1  2018    1    1     0       0       48   6601      1           0   
9   L1  2018    1    1     0       2       34   6601      1           0   

   Registro  Tipo de Registro  Especie  Classe  Comprimento  Velocidade  \
1    155621                 0        1       0           35          63   
2    155622                 0        0       0            5         100   
3    155623                 0        2       1          138          80   
4    155624                 0        1       0           37         102   
5    155625                 0        0       0            8         119   
6         1                 0        0       0           12         169   
7         2                 0        1       0           36          80   
8         3                 0        1       0           35          72   
9         4                 0        0       0           12         211   

   Ocupacao  
1      1561  
2       776  
3      2565  
4      1035  
5       723  
6       591  
7      1259  
8      1411  
9       523

In [127]:
rotulo_teste = rotular_df(df_dia_teste)
df_dia_teste['Pluviosidade (Rotulo)'] = rotulo_teste
df_dia_teste

Lote   Ano  Mes  Dia  Hora  Minuto  Segundo  Local  Faixa  Entrefaixa  \
1   L1  2017   12   31    23      58       23   6601      1           0   
2   L1  2017   12   31    23      59       27   6601      1           0   
3   L1  2017   12   31    23      59       42   6601      1           0   
4   L1  2017   12   31    23      59       48   6601      1           0   
5   L1  2017   12   31    23      59       56   6601      1           0   
6   L1  2018    1    1     0       0        0   6601      1           0   
7   L1  2018    1    1     0       0       33   6601      1           0   
8   L1  2018    1    1     0       0       48   6601      1           0   
9   L1  2018    1    1     0       2       34   6601      1           0   

   Registro  Tipo de Registro  Especie  Classe  Comprimento  Velocidade  \
1    155621                 0        1       0           35          63   
2    155622                 0        0       0            5         100   
3    155623                 0        2       1          138          80   
4    155624                 0        1       0           37         102   
5    155625                 0        0       0            8         119   
6         1                 0        0       0           12         169   
7         2                 0        1       0           36          80   
8         3                 0        1       0           35          72   
9         4                 0        0       0           12         211   

   Ocupacao  Pluviosidade (Rotulo)  
1      1561                     -2  
2       776                     -1  
3      2565                     -1  
4      1035                     -1  
5       723                     -1  
6       591                      0  
7      1259                      0  
8      1411                      0  
9       523                      2